name: Build and Package Python Lambda

on:
  workflow_call:
    inputs:
      lambda_name:
        description: The name of the Lambda function.
        required: true
        type: string
      env_name:
        description: 'Name of the environment'
        required: false
        type: string
        default: 'prod'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Validate Python scripts
      run: |
        find . -name "*.py" | xargs -I {} python -m py_compile {}
      shell: bash

    - name: Create deployment package
      run: |
        zip -r ${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip . -x "*.git*" -x "*.github*"
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.lambda_name }}-${{ inputs.env_name }}
        path: ${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip
