name: Build and Package .NET Core Lambda

on:
  workflow_call:
    inputs:
      lambda_name:
        description: The name of the Lambda function.
        required: true
        type: string
      project_dir:
        description: 'Name of the .NET Core Lambda project'
        required: true
        type: string
      env_name:
        description: 'Name of the environment'
        required: false
        type: string
        default: 'prod'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Install .NET Core Lambda tool
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Lambda project
      run: dotnet lambda package --project-location ./${{ inputs.project_dir }}  -c Release -o ./publish/${{ inputs.lambda_name }}-${{ inputs.env_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.lambda_name }}-${{ inputs.env_name }}
        path: ./publish/${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip
