name: Build and Package .NET Core Lambda

on:
  workflow_call:
    inputs:
      project_name:
        description: 'Name of the .NET Core Lambda project'
        required: true
        type: string
      zip_file_name:
        description: 'Name for the zip file'
        required: true
        type: string
      artifact_name:
        description: 'Name for the GitHub artifact'
        required: true
        type: string
      env_name:
        description: 'Name of the environment'
        required: false
        type: string
        default: 'prod'
      stack_name:
        description: 'Name of the stack'
        required: true
        type: string
      template_file:
        description: 'Path of the template file'
        required: false
        type: string
        default: '.aws/templates/lambda.yml'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Install .NET Core Lambda tool
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Lambda project
      run: dotnet lambda package --project-location ./${{ inputs.project_name }}  -c Release -o ./publish/${{ inputs.zip_file_name }}

    - name: Initialize AWS credentials from secrets
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy FeedProcessor Lambda
      uses: cosq-network/aws-cloudformation-deploy@v1.2.0
      with:
        stackName: ${{ inputs.stack_name }}
        templateFile: ${{ inputs.template_file }}
