name: Upload Layer Archive to S3

on:
    workflow_call:
      inputs:
        artifact_name:
          description: The name of the artifact
          required: true
          type: string
        archive:
          description: The file path of the layer zip file
          required: true
          type: string
        layer_name:
          description: The name of the layer
          required: true
          type: string
        S3Key:
          description: The name of the S3 bucket to upload the file to.
          required: true
          type: string
        S3Bucket:
          description: The name of the S3 bucket to upload the file to.
          required: true
          type: string
        AWS_DEFAULT_REGION:
          description: The AWS region.
          required: true
          type: string
        env_name:
          description: 'Name of the environment'
          required: false
          type: string
          default: 'prod'
        template_repo:
          description: 'Name of the common template repository for cloud formation files'
          required: false
          type: string
          default: 'cosq-network/common-aws-infrastructure'
        template_repo_ref:
          description: 'Name of the common template repository for cloud formation files'
          required: false
          type: string
          default: 'master'
        template:
          description: 'Filename with path of the template'
          required: false
          type: string
          default: .aws/templates/layer.yml
        runtime:
          description: The runtime of the Layer
          required: false
          type: string
          default: 'python3.10'
      secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.template_repo }}
          ref: ${{ inputs.template_repo_ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}-${{ inputs.env_name }}

      - name: Upload Archive to S3
        run: |
          aws s3 cp ${{ inputs.archive }} s3://${{ inputs.S3Bucket }}/${{ inputs.S3Key }}

      - name: Deploy Layer
        uses: cosq-network/aws-cloudformation-deploy@v1.2.0
        with:
          stackName: ${{ inputs.layer_name }}-${{ inputs.env_name }}
          templateFile: ${{ inputs.template }}
          parameterJSON: |
            {
              "S3Bucket": "${{ inputs.S3Bucket }}",
              "S3Key": "${{ github.repository }}/${{ inputs.env_name }}/${{github.sha}}/${{ inputs.layer_name }}-${{ inputs.env_name }}.zip",
              "COSQLayerName": "${{ inputs.layer_name }}",
              "Runtime": "${{ inputs.runtime }}",
            }
