name: Upload artifact to S3 bucket

on:
    workflow_call:
        inputs:
          artifact_name:
            description: The name of the artifact to download.
            required: true
            type: string
          zip_file_name:
            description: 'Name for the zip file'
            required: true
            type: string
          s3_bucket_name:
            description: The name of the S3 bucket to upload the file to.
            required: true
            type: string
          s3_prefix_key:
            description: The S3 prefix key to upload the file to.
            required: false
            type: string
          env_name:
            description: 'Name of the environment'
            required: false
            type: string
            default: 'prod'
        secrets:
          AWS_ACCESS_KEY_ID:
            required: true
          AWS_SECRET_ACCESS_KEY:
            required: true
          AWS_REGION:
            required: true
            

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ github.workspace }}/downloads

      # - name: Display structure of downloaded files
      #   run: ls -R
      #   working-directory: ${{ github.workspace }}/downloads

      # - name: Unzip artifact
      #   run: unzip ${{ github.workspace }}/downloads/${{ inputs.zip_file_name }}

      - name: Initialize AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 bucket
        run: aws s3 cp ${{ github.workspace }}/downloads/${{ inputs.zip_file_name }} s3://${{ inputs.s3_bucket_name }}/${{ inputs.s3_prefix_key }}/${{ inputs.zip_file_name }}

