name: Upload artifact to S3 bucket

on:
  workflow_call:
    inputs:
      lambda_name:
        description: The name of the Lambda function.
        required: true
        type: string
      runtime:
        description: The runtime of the Lambda function.
        required: true
        type: string
      handler:
        description: The handler of the Lambda function.
        required: true
        type: string
      s3_bucket_name:
        description: The name of the S3 bucket to upload the file to.
        required: true
        type: string
      api_id:
        description: The API ID.
        required: false
        type: string
      parent_resource_id:
        description: The root resource ID.
        required: false
        type: string
      resource_name:
        description: The resource name.
        required: false
        type: string
      http_method:
        description: The HTTP method.
        required: false
        type: string
      env_name:
        description: 'Name of the environment'
        required: false
        type: string
        default: 'prod'
      template_repo:
        description: 'Name of the common template repository for cloud formation files'
        required: false
        type: string
        default: 'cosq-network/common-aws-infrastructure'
      template_repo_ref:
        description: 'Name of the common template repository for cloud formation files'
        required: false
        type: string
        default: 'master'
      template:
        description: 'Filename with path of the template'
        required: false
        type: string
        default: .aws/templates/lambda.yml
      integration-template:
        description: 'Filename with path of the integration template'
        required: false
        type: string
        default: .aws/templates/lambda-api-integration.yml
      variables:
        description: 'Value to set to environmen variables of the Lambda'
        required: false
        type: string
        default: ''
      security_group_ids:
        description: 'List of security group ids as comma separated string'
        required: false
        type: string
      subnet_ids:
        description: 'List of subnet ids as comma separated string'
        required: false
        type: string
      LAMBDA_ROLE_ARN:
        description: The ARN of the Lambda role.
        required: true
        type: string
      primary_layer:
        description: 'Primary layer'
        required: false
        type: string
      secondary_layer:
        description: 'Secondary layer'
        required: false
        type: string
      tertiary_layer:
        description: 'Tertiary layer'
        required: false
        type: string
      AWS_REGION:
        description: The AWS region.
        required: true
        type: string
      use_proxy:
        description: 'Use proxy'
        required: false
        type: string
      
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.template_repo }}
          ref: ${{ inputs.template_repo_ref }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.lambda_name }}-${{ inputs.env_name }}
          path: ${{ github.workspace }}/downloads

      - name: Initialize AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Upload to S3 bucket
        run: aws s3 cp ${{ github.workspace }}/downloads/${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip s3://${{ inputs.s3_bucket_name }}/${{ github.repository }}/${{ inputs.env_name }}/${{github.sha}}/${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip

      - name: Deploy Lambda
        uses: cosq-network/aws-cloudformation-deploy@v1.2.0
        with:
          stackName: ${{ inputs.lambda_name }}-${{ inputs.env_name }}
          templateFile: ${{ inputs.template }}
          parameterJSON: |
            {
              "S3Bucket": "${{ inputs.s3_bucket_name }}",
              "S3Key": "${{ github.repository }}/${{ inputs.env_name }}/${{github.sha}}/${{ inputs.lambda_name }}-${{ inputs.env_name }}.zip",
              "FunctionName": "${{ inputs.lambda_name }}",
              "Runtime": "${{ inputs.runtime }}",
              "Handler": "${{ inputs.handler }}",
              "LambdaExecutionRoleArn": "${{ inputs.LAMBDA_ROLE_ARN }}",
              "SecurityGroupIds": "${{ inputs.security_group_ids }}",
              "SubnetIds": "${{ inputs.subnet_ids }}",
              "PrimaryLayer": "${{ inputs.primary_layer }}",
              "SecondaryLayer": "${{ inputs.secondary_layer }}",
              "TertiaryLayer": "${{ inputs.tertiary_layer }}"
            }

      - name: Configure lambda environmenr variables
        if: ${{ inputs.variables }}
        run: |
          aws lambda update-function-configuration \
          --function-name ${{ inputs.lambda_name }} \
          --environment "Variables={${{ inputs.variables }}}"

  integrate-to-api-gateway:
    needs: deploy
    if: ${{ inputs.api_id && inputs.parent_resource_id && inputs.http_method && inputs.resource_name }}
    uses: ./.github/workflows/integrate-lambda.yml
    with:
      lambda_name: ${{ inputs.lambda_name }}
      api_id: ${{ inputs.api_id }}
      parent_resource_id: ${{ inputs.parent_resource_id }}
      resource_name: ${{ inputs.resource_name }}
      http_method: ${{ inputs.http_method }}
      env_name: ${{ inputs.env_name }}
      template_repo: ${{ inputs.template_repo }}
      template_repo_ref: ${{ inputs.template_repo_ref }}
      template: ${{ inputs.integration-template }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
      use_proxy: ${{ inputs.use_proxy }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
