name: Upload artifact to S3 bucket

on:
    workflow_call:
        inputs:
            artifact_name:
              description: The name of the artifact to download.
              required: true
              type: string
            zip_file_name:
              description: 'Name for the zip file'
              required: true
              type: string
            s3_bucket_name:
              description: The name of the S3 bucket to upload the file to.
              required: true
              type: string
            s3_prefix_key:
              description: The S3 prefix key to upload the file to.
              required: false
              type: string
            s3_object_name:
              description: The S3 object name to upload the file as.
              required: false
              type: string
            env_name:
              description: 'Name of the environment'
              required: false
              type: string
              default: 'prod'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}

      - name: Unzip artifact
        run: unzip ${{ inputs.artifact_name }}
