name: Deploy Lambda Method

on:
    workflow_call:
      inputs:

        api_id:
          description: The API ID.
          required: true
          type: string

        resource_name:
          description: The resource name.
          required: true
          type: string

        resource_id_name:
          description: The resource ID name.
          required: true
          type: string

        lambda_name:
          description: The name of the Lambda function.
          required: true
          type: string

        http_method:
          description: The HTTP method.
          required: true
          type: string

        content_handling:
          description: The content handling.
          required: false
          type: string

        proxy_resource:
          description: When to have proxy resource or not
          required: false
          type: string

        proxy_path:
          description: The proxy path
          required: false
          type: string

        deploy_options:
          description: The deploy options
          required: false
          type: string

        AWS_DEFAULT_REGION:
          description: The AWS region.
          required: true
          type: string

        env_name:
          description: 'Name of the environment'
          required: false
          type: string
          default: 'dev'

        template_repo:
          description: 'Name of the common template repository for cloud formation files'
          required: false
          type: string
          default: 'cosq-network/common-aws-infrastructure'

        template_repo_ref:
          description: 'Name of the common template repository for cloud formation files'
          required: false
          type: string
          default: 'master'

        template:
          description: 'Filename with path of the template'
          required: false
          type: string
          default: .aws/templates/lambda-method.yml

      secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
jobs:
  deploy-method:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.template_repo }}
          ref: ${{ inputs.template_repo_ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda Method
        uses: cosq-network/aws-cloudformation-deploy@v1.2.0
        with:
          stackName: ${{ inputs.lambda_name }}-method-${{ inputs.env_name }}
          templateFile: ${{ inputs.template }}
          parameterJSON: |
            {
              "RestApiId": "${{ inputs.api_id }}",
              "ResourceName": "${{ inputs.resource_name }}",
              "ResourceIdName": "${{ inputs.resource_id_name }}",
              "LambdaFunctionName": "${{ inputs.lambda_name }}",
              "HTTPMethod": "${{ inputs.http_method }}",
              "ContentHandling": "${{ inputs.content_handling }}",
              "StageName": "${{ inputs.env_name }}",
              "ProxyResource": "${{ inputs.proxy_resource }}",
              "ProxyPath": "${{ inputs.proxy_path }}",
              "DeployOptions": "${{ inputs.deploy_options }}"
            }
